esphome:
  name: esphome-web-ac89bc
  friendly_name: Xiaozhi 3.5
  min_version: 2025.5.0
  name_add_mac_suffix: false

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"

psram:
  mode: octal
  speed: 80MHz

api:

ota:
  - platform: esphome
    id: ota_esphome

logger:
  level: DEBUG

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Xiaozhi 3.5 Hotspot"
    password: "RZ7D3EzJdPM6"

captive_portal:

i2c:
  - id: bus_a
    sda: GPIO8
    scl: GPIO7
    scan: true

pca9554:
  - id: pca9554a_device
    address: 0x20

switch:
  - platform: gpio
    name: "PA CTRL"
    pin:
      pca9554: pca9554a_device
      number: 7
    restore_mode: RESTORE_DEFAULT_ON

i2s_audio:
  - id: i2s_audio_bus
    i2s_lrclk_pin: GPIO15
    i2s_bclk_pin: GPIO13
    i2s_mclk_pin: GPIO12

audio_dac:
  - platform: es8311
    i2c_id: bus_a
    id: es8311_dac
    bits_per_sample: 16bit
    sample_rate: 48000

microphone:
  - platform: i2s_audio
    id: box_mic
    sample_rate: 16000
    i2s_din_pin: GPIO14
    bits_per_sample: 16bit
    adc_type: external

speaker:
  - platform: i2s_audio
    id: box_speaker
    i2s_dout_pin: GPIO16
    dac_type: external
    sample_rate: 48000
    bits_per_sample: 16bit
    channel: left
    audio_dac: es8311_dac
    buffer_duration: 100ms

media_player:
  - platform: speaker
    name: Mediaplayer
    id: external_media_player
    announcement_pipeline:
      speaker: box_speaker
      format: FLAC
      sample_rate: 48000
      num_channels: 1

spi:
  clk_pin: GPIO5
  mosi_pin: GPIO1
  miso_pin: GPIO2

output:
  - platform: ledc
    id: backlight_output
    pin: GPIO6

light:
  - platform: monochromatic
    id: Sled
    name: Screen
    output: backlight_output
    restore_mode: ALWAYS_ON

time:
  - platform: sntp
    id: sntp_time
    timezone: "Etc/UTC"

font:
  - file: "gfonts://Roboto"
    id: my_font
    size: 28
  - file: "gfonts://Roboto"
    id: roboto_52
    size: 52

binary_sensor:
  - platform: template
    name: "Touch Button"
    id: touch_input

  - platform: gpio
    pin: 
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: "Left Button"
    id: left_button
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_press:
      - logger.log: "Button was pressed"
    on_release:
      - logger.log: "Button was released"

touchscreen:
  - platform: ft63x6
    i2c_id: bus_a
    on_touch:
      then:
        - logger.log:
            format: Touch %d at (%d, %d)
            args: [touch.id, touch.x, touch.y]
        - binary_sensor.template.publish:
            id: touch_input
            state: ON
    on_release:
      then:
        - binary_sensor.template.publish:
            id: touch_input
            state: OFF

display:
  - platform: ili9xxx
    id: my_display
    model: ST7796
    dc_pin: GPIO3
    dimensions:
      width: 480
      height: 320
    transform:
      swap_xy: true
      mirror_x: false
    color_order: BGR
    invert_colors: true
    auto_clear_enabled: false
    update_interval: 1s   # <-- update every second
    lambda: |-
      auto black = Color(0,0,0), red = Color(255,0,0), green = Color(0,255,0), blue = Color(0,0,255), yellow = Color(255,255,0), white = Color(255,255, 255), cyberlightgreen = Color(0,255,159), cyberlightblue = Color(0,184,255), cyberpink = Color(214,0,255);
      it.fill(black);
      it.strftime(120, 120, id(roboto_52), cyberlightgreen, TextAlign::CENTER, "%H:%M:%S", id(sntp_time).now());
